### ISSUE TITLE
Odata Unit Test Case 

### ISSUE THREAD

**Issue by ChiraagKataria** [OData/OData.Neo#25]
Hi, 
I have been developing unit test cases for Odata that are based on parameters entered via the URL. 
While developing, I have come across the issue of how to provide the URL paramters via the MSTest collaborating with Odata enablequery attribute and AsQueryable method.

Kindly Help!

**Comment by ChiraagKataria** [comment]
Overall, I have this URL for instance, "https://localhost:port/odata/page1?filter=column eq 'value'&top=1&$skip=0"

I am able to run this with Postman, where my endpoint return is "return ok(result)" where result is the value from the context.Database_Table.AsQueryable()". So, from test method, I am unable to pass those URL paramters for filter, top or skip.
Here, I want to understand if there is a method for which how can I pass those paramters from testmethod when i initialize the httpcontext and where the controller-method works basis this.

**Comment by TehWardy** [comment]
I assume this is resolved as it seemed to be more of an in context general question.
I'm going to close this, open a new issue if you have further questions.
