### ISSUE TITLE
FOUNDATIONS: Filter Service Implementation

### ISSUE THREAD

**Issue by hassanhabib** [OData/OData.Neo#5]
*GIVEN* AS AN ENGINEER
*WHEN* I NEED TO RUN FILTERING ON MY DATA THROUGH A QUERY
*THEN* I SHOULD BE ABLE TO LEVERAGE A CAPABILITY IN ODATA NEO TO FILTER DATA FROM THE PROVIDER

**Comment by TehWardy** [comment]
What's the context here ...
   - Odata filter an IEnumerable by building an expression tree based filter?
   - OData filter a set of dat ao na sql server by adding a where clause in to a SQL query
   - OData translation to something else?
   
   It seems that through our live sessions a deeper dive is revealing that some sort of convention based handler "per target broker" is what's needed.
   
   Would you not agree?

**Comment by casperOne** [comment]
I agree with @TehWardy here; there's going to be a need between OData and the underlying provider to be able to negotiate responsibilities of the provider so that OData can know what the provider will handle and what OData will have to layer on top of the provider.
